project: ivtlr
save_path: /path/IVT-LR/qwen_vl_2b/
name: qwen2b_IVTLR

epochs_per_stage: 4
max_latent_stage: 5
pad_latent_to_max: True

load_model_path: None
seed: 0
resume: 0
bf16: True
batch_size_training: 16
debug: False
gradient_accumulation_steps: 8
num_epochs: 16
lr: !!float "4e-5"
patch_reuse_policy: never
enable_nvt_loss: True
nvt_loss_weight: 0.1
nvt_loss_epsilon: 1e-8